#!/bin/bash

##
# e.g. ./bulk-load synthea 127.0.0.1 5432 postgres sa /path/to/data/dir /path/to/vocab

DB=$1
HOSTNAME=$2
PORT=$3
## this is hardcoded into SQL scripts anyway
#NATIVE=$3
NATIVE=native
#CDM=$4
CDM=cdm_synthea10

USERNAME=$4
PASSWORD=$5
DATA_DIRECTORY=$6
VOCAB_DIRECTORY=$7 


echo "creating synthea tables"
psql -c "CREATE SCHEMA $NATIVE" "postgresql://$USERNAME:$PASSWORD@$HOSTNAME:${PORT}/$DB"
PGOPTIONS="--search_path=$NATIVE" psql -f "ETL/SQL/synthea_ddl.sql" "postgresql://$USERNAME:$PASSWORD@$HOSTNAME:${PORT}/$DB" 

echo "creating cdm tables"
psql -c "CREATE SCHEMA $CDM" "postgresql://$USERNAME:$PASSWORD@$HOSTNAME:${PORT}/$DB"
PGOPTIONS="--search_path=$CDM" psql -f "ETL/SQL/drop_cdm_tables.sql" "postgresql://$USERNAME:$PASSWORD@$HOSTNAME:${PORT}/$DB" 
PGOPTIONS="--search_path=$CDM" psql -f "ETL/SQL/cdm_v5.3_ddl.sql" "postgresql://$USERNAME:$PASSWORD@$HOSTNAME:${PORT}/$DB" 

echo "loading data from synthea csv files to relational database"
for TABLE in allergies careplans conditions encounters immunizations medications observations patients procedures
do
PGOPTIONS="--search_path=$NATIVE" psql -c "\copy $TABLE from '$DATA_DIRECTORY/$TABLE.csv' CSV HEADER" "postgresql://$USERNAME:$PASSWORD@$HOSTNAME:${PORT}/$DB" 
done

echo "loading data from vocab csv files to relational database"
for TABLE in CONCEPT CONCEPT_ANCESTOR CONCEPT_RELATIONSHIP CONCEPT_CLASS CONCEPT_SYNONYM DOMAIN DRUG_STRENGTH RELATIONSHIP VOCABULARY
do
PGOPTIONS="--search_path=$CDM" psql -c "\copy $TABLE from '$VOCAB_DIRECTORY/$TABLE.csv' CSV DELIMITER E'\t' QUOTE E'\b' HEADER" "postgresql://$USERNAME:$PASSWORD@$HOSTNAME:${PORT}/$DB" 
done

echo "creating vocab maps..."

PGOPTIONS="--search_path=$CDM" psql -f "ETL/SQL/create_source_to_source_vocab_map.sql" "postgresql://$USERNAME:$PASSWORD@$HOSTNAME:${PORT}/$DB"

PGOPTIONS="--search_path=$CDM" psql -f "ETL/SQL/create_source_to_standard_vocab_map.sql" "postgresql://$USERNAME:$PASSWORD@$HOSTNAME:${PORT}/$DB"

echo "creating visit logic tables..."

PGOPTIONS="--search_path=$CDM" psql -f "ETL/SQL/AllVisitTable.sql" "postgresql://$USERNAME:$PASSWORD@$HOSTNAME:${PORT}/$DB"

PGOPTIONS="--search_path=$CDM" psql -f "ETL/SQL/AAVITable.sql" "postgresql://$USERNAME:$PASSWORD@$HOSTNAME:${PORT}/$DB"

PGOPTIONS="--search_path=$CDM" psql -f "ETL/SQL/final_visit_ids.sql" "postgresql://$USERNAME:$PASSWORD@$HOSTNAME:${PORT}/$DB"

echo "Performing ETL"

# echo "Loading location"
# PGOPTIONS="--search_path=$CDM" psql -f "ETL/SQL/insert_location.sql" "postgresql://$USERNAME:$PASSWORD@$HOSTNAME/$DB" 

echo "Loading person"
PGOPTIONS="--search_path=$CDM" psql -f "ETL/SQL/insert_person.sql" "postgresql://$USERNAME:$PASSWORD@$HOSTNAME:${PORT}/$DB" 

# echo "Loading death"
# PGOPTIONS="--search_path=$CDM" psql -f "ETL/SQL/insert_death.sql" "postgresql://$USERNAME:$PASSWORD@$HOSTNAME/$DB" 

echo "Loading observation_period"
PGOPTIONS="--search_path=$CDM" psql -f "ETL/SQL/insert_observation_period.sql" "postgresql://$USERNAME:$PASSWORD@$HOSTNAME:${PORT}/$DB" 

echo "Loading visit_occurrence"
PGOPTIONS="--search_path=$CDM" psql -f "ETL/SQL/insert_visit_occurrence.sql" "postgresql://$USERNAME:$PASSWORD@$HOSTNAME:${PORT}/$DB" 

echo "Loading observation"
PGOPTIONS="--search_path=$CDM" psql -f "ETL/SQL/insert_observation.sql" "postgresql://$USERNAME:$PASSWORD@$HOSTNAME:${PORT}/$DB" 

echo "Loading condition_occurrence"
PGOPTIONS="--search_path=$CDM" psql -f "ETL/SQL/insert_condition_occurrence.sql" "postgresql://$USERNAME:$PASSWORD@$HOSTNAME:${PORT}/$DB" 

echo "Loading procedure_occurrence"
PGOPTIONS="--search_path=$CDM" psql -f "ETL/SQL/insert_procedure_occurrence.sql" "postgresql://$USERNAME:$PASSWORD@$HOSTNAME:${PORT}/$DB" 

echo "Loading measurement"
PGOPTIONS="--search_path=$CDM" psql -f "ETL/SQL/insert_measurement.sql" "postgresql://$USERNAME:$PASSWORD@$HOSTNAME:${PORT}/$DB" 

echo "Loading drug exposure"
PGOPTIONS="--search_path=$CDM" psql -f "ETL/SQL/insert_drug_exposure.sql" "postgresql://$USERNAME:$PASSWORD@$HOSTNAME:${PORT}/$DB" 

echo "Loading condition_era"
PGOPTIONS="--search_path=$CDM" psql -f "ETL/SQL/insert_condition_era.sql" "postgresql://$USERNAME:$PASSWORD@$HOSTNAME:${PORT}/$DB" 

echo "Loading drug_era"
PGOPTIONS="--search_path=$CDM" psql -f "ETL/SQL/insert_drug_era.sql" "postgresql://$USERNAME:$PASSWORD@$HOSTNAME:${PORT}/$DB" 

# PGOPTIONS="--search_path=$CDM" psql -f "ETL/SQL/cdm_v5.3_indexes_ddl.sql" "postgresql://$USERNAME:$PASSWORD@$HOSTNAME/$DB" 

# PGOPTIONS="--search_path=$CDM" psql -f "ETL/SQL/cdm_v5.3_constraints_ddl.sql" "postgresql://$USERNAME:$PASSWORD@$HOSTNAME/$DB" 


# TODO - Either create a staging schema for native Synthea tables or drop the Synthea tables after ETL complete
